### ISSUE TITLE
Using gtkmm3.1.6 X64 binaries with vs2013 update 4.

### ISSUE THREAD

**Issue by deltamish** [codekiddy2/Visual-Studio-gtkmm#1]
Hi,

I downloaded the copy of your binary package.. But when i set up include files and the property shett.. 
I get around 100 errors.. Saying something like 

function returning function not allowed 

identifier gsize is undefined
identifier gint32 is undefined 
.........

can you please help me out here..

**Comment by codekiddy2** [comment]
Hello deltamish,

I'm not sure how and why you get these errors since you didn't provide what procedure from the "readme" file you followed.

When you extract the binaries package there is a readme file offering 3 possible options to perform the initial setup.

Please make sure you read this file after extracting the package and then please carefully follow 
the "Option 2" from readme file and report results.

Can you confirm that "Option 2" works for you?

**Comment by deltamish** [comment]
Hi,
That old project somehow got deleted
I created a new project and just to know that i am on the right path..
After using "Add existing property file"

I go to vc++ directories and add each every subfolder inside the Include folder "
right

**Comment by codekiddy2** [comment]
After using "Add existing property file" there is nothing else you need to do, just make sure the property file is added to debug x64 configuration AND that you build debug x64 configuration.

You do not need to modify the property file at all.
Just to make sure, we are talking about Option 2 here? ...

Does that work?

**Comment by deltamish** [comment]
Ohh okay.. I started fresh .. I added the property file and a basic script..

#include<iostream>
#include<gtkmm.h>
#include<gtkmm\application.h>

using namespace Gtk;

int main(int argc, char\* argv[])
{
    Glib::RefPtrGtk::Application  app = Gtk::Application::create(argc, argv, "Test");
    Window wind;
    wind.set_default_size(300, 300);
    Gtk::Main::run(wind);
    return 0;
}

But i get following errors 

Error   10  error LNK1120: 9 unresolved externals  
Error   4   error LNK2019: unresolved external symbol "__declspec(dllimport) protected: virtual __thiscall Glib::ObjectBase::~ObjectBase(void)" (__imp_??1ObjectBase@Glib@@MAE@XZ) referenced in function "public: void __thiscall Gtk::Window::`vbase destructor'(void)" (??_DWindow@Gtk@@QAEXXZ)  
Error   3   error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall sigc::trackable::~trackable(void)" (__imp_??1trackable@sigc@@QAE@XZ) referenced in function "public: void __thiscall Gtk::Window::`vbase destructor'(void)" (??_DWindow@Gtk@@QAEXXZ)    

.........

**Comment by codekiddy2** [comment]
I still didn't get your confirmation if you use "Option 2" which says following:

OPTION 2: extract this package into C:\ so that you end up with C:\gtkmm3_debug_64_VS_2013\ and use provided property sheet gtkmm3-debug-x64.props to create and build new projects.

Did you do so?

**Comment by codekiddy2** [comment]
BTW You should replace following:

Gtk::Main::run(wind);
return 0;

with:

return app->run(wind);

**Comment by deltamish** [comment]
Hi,

Thank you soo much for trying to help me out..

I  followed  step 2 ..
And i replaced
Gtk::Main:;run(wind);

 with

return app->run(wind);

But still i get the same errors

Thanks

**Comment by codekiddy2** [comment]
Hi, sorry for delay...I had to go to work...

The errors you're are getting are linker errors, here are few tips/steps you can try out to fix this:
- Make sure the package is extracted into C drive "C:\gtkmm3_debug_64_VS_2013\"
- Create new project and add debug x64 configuration to project by using Configuration manager
- Then add property sheet to debug x64 node in property manager
- Make no other settings to project (except adding code) and hit build solution

Other than that try to manually link libraries in project settings from the package until all unresolved externals go away.
Make sure platform toolset is Visual Studio 2013 (v120) in project properties.

I hope that helps

**Comment by deltamish** [comment]
Hi,
Thank you so much  again

Looks like it was a problem with vs2013 itself.. Today when i opened it .It miraculously
compiled without errors .But crashes saying that it couldnt
Find _gtkmm.dll_

SO should i manually link the files or is there  a cheap workaround.

Thanks

**Comment by codekiddy2** [comment]
gtkmm.dll and other dll's can't be found probably because they are not in PATH.

go to Control Panel\All Control Panel Items\System
click on Advanced system settings then environment variables
under "system variables" add 
C:\gtkmm3_debug_64_VS_2013\bin to PATH variable separating it with semicolon
make sure not to delete existing entries from PATH

once done Visual Studio must be restarted for changes to take effect.

**Comment by deltamish** [comment]
Thanks It worked..

I was such an idiot and i never realized to add the folder to the path variable..

Thanks
