### ISSUE TITLE
Using custom loop for Gtk rather than Gtk::run

### ISSUE THREAD

**Issue by deltamish** [codekiddy2/Visual-Studio-gtkmm#2]
Hi,

I have been experimenting with Gtk for a while and its very powerful .But there is one problem Gtk uses an internal loop to run its application ..I wanted to use my own loop toi run gtk so that i can also use it for rendering in DX11 like a 3d engine

Is there a way so that i can override the function to use my own loop 

Eg

int main()
{
// All initialization stuffs and creat app(Gtk:;Application)
   return app->run(window);
}

I thought some thing like 

int main()
{
 // Create Gtk::Aplication
 while(true)
{
 app->RunOnce(window); // where the functuion draws only when in my custom while loop., or else draws once

CreateD3DDevice();
UpdateLogic();
RenderinWindow();
}

}

Thanks

**Comment by codekiddy2** [comment]
This question is more suitable for gtkmm mailing list.
You should get better answer there.
